core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('balance.urls')),
    path('expense/', include('expense.urls')),
    path('income/', include('income.urls')),
    path('category/', include('category.urls')),
]

expense/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('add', views.add, name='add'),
    path('edit/<int:id>', views.edit, name='edit'),
    path('details/<int:id>', views.details, name='details'),
    path('delete/<int:id>', views.delete, name='delete'),
]

expense/models.py
from django.db import models
from category.models import ExpenseCategory
from category.models import ExpenseSubCategory
from django.utils.translation import gettext as _
import datetime

# Create your models here.

class Expense(models.Model):
    category = models.ForeignKey(ExpenseCategory, on_delete=models.SET_NULL, null=True, blank=True)
    subcategory = models.ForeignKey(ExpenseSubCategory, on_delete=models.SET_NULL, null=True, blank=True)
    methodofpayment = models.ForeignKey('MethodOfPayment', on_delete=models.SET_NULL, null=True, blank=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    date = models.DateField(_("Date"), default=datetime.date.today)
    description = models.TextField(null=True, blank=True)
    
    # Not working because ordering is already set in views.py: ".order_by('date', 'amount')"
    # class Meta:
    #     ordering = ['-date', '-amount']
    
    def __str__(self):
        return f"{self.amount}  - {self.category.name} - {self.subcategory.name if self.subcategory else 'No Subcategory'}"
    
    def get_transaction_type(self):
        return "Expense"

class MethodOfPayment(models.Model):
    method = models.CharField(max_length=100)

    def __str__(self):
        return self.method

expense/forms.py
from django import forms
from .models import Expense

class DateInput(forms.DateInput):
    input_type = 'date'

class ExpenseForm(forms.ModelForm):
    class Meta:
        model = Expense
        fields = ["category", "subcategory", "methodofpayment", "amount", "date", "description"]
        widgets = {
            "category": forms.Select(attrs={"class": "form-select"}),
            "subcategory": forms.Select(attrs={"class": "form-select"}),
            "methodofpayment": forms.Select(attrs={"class": "form-select"}),
            "amount": forms.NumberInput(attrs={"class": "form-control"}),
            "date": DateInput(attrs={"class": "form-control"}),
            "description": forms.Textarea(attrs={"class": "form-control", "rows": 3}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Set the default value for methodofpayment
        self.fields["methodofpayment"].initial = 1  # default value is card

expense/views.py
from .models import Expense
from django.shortcuts import render, redirect
from .forms import ExpenseForm
from django.db.models import Min, Max
import calendar
import datetime

# Create your views here.

def index(request):
    # Get the current date
    current_date = datetime.date.today()

    # Get month, year, and order from the request, or use the latest month and year if not provided
    month = request.GET.get('month')
    year = request.GET.get('year')
    order = request.GET.get('order', '')

    if not month and not year:
        # Default to the latest month and year
        month = current_date.month
        year = current_date.year
    else:
        # Convert to integers if provided
        month = int(month) if month and month.isdigit() else None
        year = int(year) if year and year.isdigit() else current_date.year

    # Finding min and max year from the database.
    year_range = Expense.objects.aggregate(min_year=Min('date__year'), max_year=Max('date__year'))
    years = range(year_range['min_year'], year_range['max_year'] + 1)
    months = [(i, calendar.month_name[i]) for i in range(1, 13)]

    # Filter expenses for the selected or current month and year
    if month:
        myexpenses = Expense.objects.filter(date__year=year, date__month=month)
    else:
        myexpenses = Expense.objects.filter(date__year=year)
        
    # ordering by amount
    if order == 'asc':
        myexpenses = myexpenses.order_by('amount', '-date').select_related('category', 'subcategory', 'methodofpayment')
    elif order == 'desc':
        myexpenses = myexpenses.order_by('-amount', '-date').select_related('category', 'subcategory', 'methodofpayment')
    else:
        myexpenses = myexpenses.order_by('-date', 'amount').select_related('category', 'subcategory', 'methodofpayment')

    context = {
        'myexpenses': myexpenses,
        'order': order,
        'months': months,
        'month_selected': month,
        'years': years,
        'year_selected': year,
    }
    return render(request, 'expense/index.html', context)


def add(request):
    form = ExpenseForm()
    
    if request.method == 'POST':
        form = ExpenseForm(request.POST)
        print(request.POST)
        if form.is_valid():
            form.save()
            print('Form is successfully. It work!')
            return redirect('/expense')
        else:
            print('Error')
            print('Form errors:', form.errors)
        
    context = {'form': form}
    return render(request, 'expense/add.html', context)

def edit(request, id):
    expense = Expense.objects.get(id=id)
    form = ExpenseForm(instance=expense)
    
    if request.method == 'POST':
        form = ExpenseForm(request.POST, instance=expense)
        if form.is_valid():
            form.save()
            return redirect('/expense')
    
    context = {'form': form}
    return render(request, 'expense/edit.html', context)
    
def details(request, id):
    myexpense = Expense.objects.get(id=id)
    context = {
        'myexpense': myexpense,
    }
    return render(request, 'expense/details.html', context)
    
def delete(request, id):
    expense = Expense.objects.get(id=id)
    if request.method == 'POST':
        expense.delete()
        return redirect('/expense')
    return render(request, 'expense/delete.html', {'obj':expense})

templates/expense/add.html
{% extends "base.html" %}
{% block title %}Add expense{% endblock title %}

{% block content %}
<h2 class="clr p-3">Add expense</h2>

<div class="mt-3">
    <form method="POST" action="">
        {% csrf_token %}
        <div class="row g-3">
            <div class="col-md-6">
                <div class="form-floating">
                    {{ form.category }}
                    <label for="id_category">{{ form.category.label }}</label>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-floating">
                    {{ form.subcategory }}
                    <label for="id_subcategory">{{ form.subcategory.label }}</label>
                </div>
            </div>
        </div>
        <div class="row g-3 mt-3">
            <div class="col-md-6">
                <div class="form-floating">
                    {{ form.methodofpayment }}
                    <label for="id_methodofpayment">{{ form.methodofpayment.label }}</label>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-floating">
                    {{ form.amount }}
                    <label for="id_amount">{{ form.amount.label }}</label>
                </div>
            </div>
        </div>
        <div class="row g-3 mt-3">
            <div class="col-md-6">
                <div class="form-floating">
                    {{ form.date }}
                    <label for="id_date">{{ form.date.label }}</label>
                </div>
            </div>
        </div>
        <div class="row g-3 mt-3">
            <div class="col-12">
                <div class="form-floating">
                    {{ form.description }}
                    <label for="id_description">{{ form.description.label }}</label>
                    <style>
                        #id_description {
                            height: 100px;
                        }
                    </style>
                </div>
            </div>
        </div>
        <button type="submit" class="btn btn-outline-primary mt-4">Submit</button>
    </form>
</div>

<script>
document.addEventListener("DOMContentLoaded", function() {
    const categorySelect = document.getElementById('id_category');
    const subcategorySelect = document.getElementById('id_subcategory');
    subcategorySelect.disabled = true; // disable selecting subcategory before category

    categorySelect.onchange = function() {
        const categoryId = this.value;
        if (categoryId) {
            subcategorySelect.disabled = false; // enable selecting subcategory
            fetch(`{% url 'category_subcategories' %}?category_id=${categoryId}`)
                .then(response => response.json())
                .then(data => {
                    subcategorySelect.innerHTML = '<option value="">Select a subcategory</option>';
                    data.subcategories.forEach(function(sub) {
                        const option = new Option(sub.name, sub.id);
                        subcategorySelect.add(option);
                    });
                })
                .catch(error => console.error('Error loading the subcategories:', error));
        } else {
            subcategorySelect.disabled = true; // disable selecting subcategory
            subcategorySelect.innerHTML = '<option value="">Select a subcategory</option>';
        }
    };
});
</script>
{% endblock %}

templates/expense/delete.html
{% extends "base.html" %}

{% block content %}

<h2>Delete expense</h2>

    <form method="POST" action="">
        <a href="{{request.META.HTTP_REFERER}}" class="btn btn-primary">Go back</a>
        {% csrf_token %}
        <p>Are you sure you want to delete "{{obj}}"?</p>
        <button type="submit" value="Confirm" class="btn btn-danger">Submit</button>
    </form>

{% endblock content%}

templates/expense/details.html
{% extends "base.html" %}
{% block title %}Details{% endblock title %}

{% block content %}
<div>
    <h1 class="mb-3">Details Page</h1>
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Expense Details</h4>
            <p class="card-text"><strong>Amount:</strong> {{ myexpense.amount }}</p>
            <p class="card-text"><strong>Description:</strong> {{ myexpense.description }}</p>
            <p class="card-text"><strong>Category:</strong> {{ myexpense.category }}</p>
            <p class="card-text"><strong>Subcategory:</strong> {{ myexpense.subcategory }}</p>
            <p class="card-text"><strong>Method of Payment:</strong> {{ myexpense.methodofpayment }}</p>
            <p class="card-text"><strong>Date:</strong> {{ myexpense.date|date:"d. F Y"}}</p>
        </div>
        <div class="card-footer">
            <a href="/expense/edit/{{ myexpense.id }}" class="btn btn-primary">Edit</a>
            <a href="/expense/delete/{{ myexpense.id }}" class="btn btn-danger">Delete</a>
        </div>
    </div>
</div>
{% endblock %}

templates/expense/edit.html
{% extends "base.html" %}
{% block title %}Edit Expense{% endblock title %}

{% block content %}
<div>
  <h2>Edit expense</h2>

  <form method="post" action="">
    {% csrf_token %}
    <div class="mb-3">
      <label for="{{ form.category.id_for_label }}" class="form-label">Category</label>
      {{ form.category }}
    </div>
    <div class="mb-3">
      <label for="{{ form.subcategory.id_for_label }}" class="form-label">Subcategory</label>
      {{ form.subcategory }}
    </div>
    <div class="mb-3">
      <label for="{{ form.methodofpayment.id_for_label }}" class="form-label">Method of payment</label>{{ form.methodofpayment }}</div>
    <div class="mb-3">
      <label for="{{ form.amount.id_for_label }}" class="form-label">Amount</label>
      {{ form.amount }}
    </div>
    <div class="mb-3">
      <label for="{{ form.description.id_for_label }}" class="form-label">Description</label>
      {{ form.description }}
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>

</div>

<script>
  document.addEventListener("DOMContentLoaded", function() {
    const categorySelect = document.getElementById('id_category');
    const subcategorySelect = document.getElementById('id_subcategory');
    const initialSubcategoryId = "{{ form.subcategory.value }}";

    function updateSubcategories(categoryId, defaultSubcategoryId = null) {
      fetch(`{% url 'category_subcategories' %}?category_id=${categoryId}`)
        .then(response => response.json())
        .then(data => {
          subcategorySelect.innerHTML = '<option value="">Select a subcategory</option>';
          data.subcategories.forEach(sub => {
            const option = new Option(sub.name, sub.id, sub.id === parseInt(defaultSubcategoryId));
            subcategorySelect.add(option);
          });
          if (defaultSubcategoryId) {
            subcategorySelect.value = defaultSubcategoryId;
          }
        })
        .catch(error => console.error('Error loading the subcategories:', error));
    }

    if (categorySelect.value) {
      updateSubcategories(categorySelect.value, initialSubcategoryId);
    }

    categorySelect.onchange = function() {
      updateSubcategories(this.value);
    };
  });
</script>
{% endblock %}

templates/expense/index.html
{% extends 'base.html' %}
{% block title %}Expenses{% endblock %}

{% block content %}
<div>
    <h2 class="mb-4 clr p-3">All expenses</h2>

    <form method="get" action="" id="filter-form" class="row g-3 mb-4 align-items-end">
        <div class="col-md-4">
            <label for="month-select" class="form-label">Month</label>
            <select id="month-select" name="month" class="form-select">
                <option value="" {% if not month_selected %}selected{% endif %}>All</option>
                {% for num, name in months %}
                <option value="{{ num }}" {% if num == month_selected %}selected{% endif %}>{{ name }}</option>
                {% endfor %}
            </select>
            
        </div>
        <div class="col-md-4">
            <label for="year-select" class="form-label">Year</label>
            <select id="year-select" name="year" class="form-select">
                {% for i in years %}
                <option value="{{ i }}" {% if i == year_selected %}selected{% endif %}>{{ i }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="col-md-3">
            <label for="order-select" class="form-label">Order by Amount</label>
            <select id="order-select" name="order" class="form-select">
                <option value="" {% if not order %}selected{% endif %}>None</option>
                <option value="asc" {% if order == 'asc' %}selected{% endif %}>Min to Max</option>
                <option value="desc" {% if order == 'desc' %}selected{% endif %}>Max to min</option>
            </select>
        </div>
    </form>

    <table class="table table-striped table-bordered table-hover">
        <thead class="table-white">
            <tr>
                <th>Amount</th>
                <th>Category</th>
                <th class="d-none d-sm-table-cell">Subcategory</th>
                <th class="d-none d-sm-table-cell">Date</th>
                <th>Description</th>
            </tr>
        </thead>
        <tbody>
            {% for expense in myexpenses %}
            <tr>
                <td>{{expense.amount}}</td>
                <td>{{expense.category.name}}</td>
                <td class="d-none d-sm-table-cell">{{expense.subcategory.name}}</td>
                <td class="d-none d-sm-table-cell">{{expense.date}}</td>
                <td class="d-sm-table-cell text-center bg-light">
                    <a href="/expense/details/{{ expense.id }}" class="btn btn-outline-primary text-decoration-none">Details</a>
                </td>
                            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>


<script>
    document.addEventListener('DOMContentLoaded', function () {
        const form = document.getElementById('filter-form');
        const selects = form.querySelectorAll('select');

        selects.forEach(select => {
            select.addEventListener('change', function () {
                form.submit();
            });
        });
    });
</script>
{% endblock %}