category/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('addIncomeCategory', views.addIncomeCategory, name='addIncomeCategory'),
    path('addExpenseCategory', views.addExpenseCategory, name='addExpenseCategory'),
    path('subcategories/', views.subcategories, name='category_subcategories'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('balance.urls')),
    path('expense/', include('expense.urls')),
    path('income/', include('income.urls')),
    path('category/', include('category.urls')),
]

category/models.py
from django.db import models

# Create your models here.
class ExpenseCategory(models.Model):
    name = models.CharField(max_length=100)
    
    def __str__(self):
        return self.name

class ExpenseSubCategory(models.Model):
    name = models.CharField(max_length=100)
    parent_category = models.ForeignKey(ExpenseCategory, on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    
class IncomeCategory(models.Model):
    name = models.CharField(max_length=100)
    
    def __str__(self):
        return self.name

class ExpenseCompanies(models.Model):
    name = models.CharField(max_length=255)
    categories = models.ManyToManyField(ExpenseCategory)
    # parent_category = models.ForeignKey(ExpenseCategory, on_delete=models.CASCADE)

    def __str__(self):
        # return self.name
        return f"{self.name}  - {self.categories}"

category/forms.py
from django.forms import ModelForm
from .models import IncomeCategory, ExpenseCategory, ExpenseSubCategory, ExpenseCompanies

class IncomeCategoryForm(ModelForm):
    class Meta:
        model = IncomeCategory
        fields = '__all__'

class ExpenseCategoryForm(ModelForm):
    class Meta:
        model = ExpenseCategory
        fields = '__all__'
        
class ExpenseSubCategoryForm(ModelForm):
    class Meta:
        model = ExpenseSubCategory
        fields = '__all__'
        
class ExpenseCompaniesForm(ModelForm):
    class Meta:
        model = ExpenseCompanies
        fields = '__all__'

category/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect
from .models import IncomeCategory, ExpenseCategory, ExpenseSubCategory
from .forms import IncomeCategoryForm, ExpenseCategoryForm, ExpenseSubCategoryForm

# Create your views here.

def index(request):
    income_categories = IncomeCategory.objects.order_by('name').all()
    expense_categories = ExpenseCategory.objects.order_by('name').all()
    expense_subcategories = ExpenseSubCategory.objects.order_by('name').all()
    
    context = {
        'income_categories': income_categories,
        'expense_categories': expense_categories,
        'expense_subcategories': expense_subcategories
    }
    return render(request, 'category/index.html', context)

    # select a subcategory depend on the selected category
def subcategories(request):
    category_id = request.GET.get('category_id')
    subcategories = ExpenseSubCategory.objects.filter(parent_category_id=category_id).values('id', 'name')
    return JsonResponse({'subcategories': list(subcategories)})

def addIncomeCategory(request):
    form = IncomeCategoryForm()
    income_categories = IncomeCategory.objects.order_by('name').all()

    
    if request.method == 'POST':
        form = IncomeCategoryForm(request.POST)
        print(request.POST)
        if form.is_valid():
            form.save()
            print('Income Category added.')
            return redirect('/category')
        else:
            print('Form errors:', form.errors)
        
    context = {
        'form': form,
        'income_categories': income_categories
        }
    return render(request, 'category/addIncomeCategory.html', context)

def addExpenseCategory(request):
    form = ExpenseCategoryForm()
    expense_categories = ExpenseCategory.objects.order_by('name').all()
    
    if request.method == 'POST':
        form = ExpenseCategoryForm(request.POST)
        print(request.POST)
        if form.is_valid():
            form.save()
            print('Expense Category added.')
            return redirect('/category')
        else:
            print('Form errors:', form.errors)
        
    context = {
        'form': form,
        'expense_categories': expense_categories
        }
    return render(request, 'category/addExpenseCategory.html', context)

templates/category/addExpenseCategory.html
{% extends "base.html" %}
{% block title %}Add expense category{% endblock title %}

{% block content %}

    <h1 class="mt-3">Add Expense Category</h1>

    <form method="POST" action="">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>

    <h2 class="mt-5">Current expense categories list</h2>

        <ul class="list-group">
            {% for category in expense_categories %}
            <li class="list-group-item d-flex justify-content-between align-items-start">
                    <div class="ms-2 me-auto">
                        <div class="fw-bold">{{category.name}}</div>
                </li>
            {% endfor %}    
        </ul>
{% endblock %}

templates/category/addIncomeCategory.html
{% extends "base.html" %}
{% block title %}Add income category{% endblock title %}

{% block content %}

    <h1 class="mt-3">Add Income Category</h1>

    <form method="POST" action="">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>

    <h2 class="mt-5">Current income categories list</h2>

        <ul class="list-group">
            {% for category in income_categories %}
            <li class="list-group-item d-flex justify-content-between align-items-start">
                    <div class="ms-2 me-auto">
                        <div class="fw-bold">{{category.name}}</div>
                </li>
            {% endfor %}    
        </ul>
{% endblock %}

templates/category/index.html
{% extends "base.html" %}
{% block title %}Categories{% endblock title %}

{% block content %}
        
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" href="/category/addIncomeCategory">Add Income Category</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/category/addExpenseCategory">Add Expense Category</a>
            </li>
        </ul>
        
        <h2 class="mt-3">Category List</h2>
        
        <ul class="list-group">
        {% for category in expense_categories %}
        <li class="list-group-item d-flex justify-content-between align-items-start">
            <div class="ms-2 me-auto">
                <div class="fw-bold">{{category.name}}</div>
                {% for subcategory in category.expensesubcategory_set.all %}  
                <ul>{{ subcategory.name }}</ul>
                {% empty %}
                {% comment %} <li>No subcategories</li> {% endcomment %}
                {% endfor %}                 </div>
                <span class="badge bg-primary rounded-pill"></span>
            </li>
            {% endfor %}    
        </ul>

{% endblock %}